### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by StatML** [IcewineChen/pytorch-PyraNet#2]
Hi @IcewineChen Can you share a pre-trained model? Thanks a lot!

**Comment by IcewineChen** [comment]
Sure.Here is the link of baidudisk: https://pan.baidu.com/s/1mRdB6BOxJfobfG7WmrkcYA and Extract code:t7b4.

**Comment by IcewineChen** [comment]
> Hi @IcewineChen Can you share a pre-trained model? Thanks a lot!
Sure.Here is the link of baidudisk: https://pan.baidu.com/s/1mRdB6BOxJfobfG7WmrkcYA and Extract code:t7b4.

**Comment by HenryJunW** [comment]
Hello @IcewineChen I am wondering whether this pretrained model uses the arch of hg? Because when I run it, it pops up the error, ImportError: No module named hg.

**Comment by HenryJunW** [comment]
Can you successfully load the pre-trained model @StatML

**Comment by HenryJunW** [comment]
Which PRM module are you using for the pretrained model?
