### ISSUE TITLE
Visualizing the results on the test image

### ISSUE THREAD

**Issue by bchou** [IcewineChen/pytorch-PyraNet#4]
Is there a way to visualize the estimates on the original test image?

**Comment by bchou** [comment]
Got the outputs from "preds.mat".

**Comment by HenryJunW** [comment]
Hello, did you train the network by yourself and test it, or test by using the pre-trained model provided? Thanks.

**Comment by bchou** [comment]
I trained the network myself using the MPII dataset. I was not able to access the pre-trained model.

**Comment by HenryJunW** [comment]
I see, may I ask what the performance of mpii is you got?

**Comment by HenryJunW** [comment]
The reason I asked about your result is that I cannot successfully load the pre-trained model. My own trained performance is around 85 after 160 epochs. I am wondering whether you get a better result. Thanks.

**Comment by bchou** [comment]
Sorry, I don't remember the exact number, but it is similar to what you have.
